#!/usr/bin/env python3
"""
Spaghetti plot: Chicago vs top 10 synthetic control donors.
Uses users/capita for visual comparability across ZIP3s.
Donors in gray, Chicago in red.
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from pathlib import Path
from load_chatgpt_data import get_output_dir

# Output directory from settings
outdir = get_output_dir()

# Load panel data
panel = pd.read_stata(Path('data/synth_panel.dta'))

# Load donor weights from CSV (generated by extract_donor_weights.py)
weights_path = outdir / 'synth_donor_weights.csv'
if weights_path.exists():
    weights = pd.read_csv(weights_path, dtype={'zip3': str})
    weights['zip3'] = weights['zip3'].str.zfill(3)
    top_donors = weights.head(10)['zip3'].tolist()
else:
    raise FileNotFoundError(f"Run extract_donor_weights.py first: {weights_path}")

# Ensure Chicago is included
plot_zip3s = top_donors + ['606']

# Filter panel to these ZIP3s
plot_data = panel[panel['zip3'].isin(plot_zip3s)].copy()

# Convert month_num to actual date for x-axis
# month_num 3 = Mar 2023, month_num 10 = Oct 2023, etc.
plot_data['date'] = pd.to_datetime('2023-01-01') + pd.to_timedelta((plot_data['month_num'] - 1) * 30.44, unit='D')

# Better: use month_dt if available
if 'month_dt' in plot_data.columns:
    plot_data['date'] = pd.to_datetime(plot_data['month_dt'], unit='ms')

# Create figure
fig, ax = plt.subplots(figsize=(12, 7))

# Plot donor ZIP3s in gray (log users) with labels
for zip3 in top_donors:
    df = plot_data[plot_data['zip3'] == zip3].sort_values('date')
    ax.plot(df['date'], df['log_users'], color='gray', alpha=0.5, linewidth=1)
    # Label at end of line
    last_pt = df.iloc[-1]
    ax.annotate(zip3, (last_pt['date'], last_pt['log_users']),
                fontsize=8, color='gray', va='center')

# Plot Chicago in red on top
chicago = plot_data[plot_data['zip3'] == '606'].sort_values('date')
ax.plot(chicago['date'], chicago['log_users'], color='red', linewidth=2, label='Chicago (606)')
# Label Chicago
last_chi = chicago.iloc[-1]
ax.annotate('606', (last_chi['date'], last_chi['log_users']),
            fontsize=8, color='red', fontweight='bold', va='center')

# Add treatment line
treatment_date = pd.Timestamp('2023-10-01')
ax.axvline(treatment_date, color='black', linestyle='--', linewidth=1, label='Tax (Oct 2023)')

# Format x-axis with month labels
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=3))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))
plt.xticks(rotation=45, ha='right')

# Labels
ax.set_xlabel('')
ax.set_ylabel('Log(Unique Users)')
ax.set_title('ChatGPT Subscribers (Log)\n(Gray = top 10 SC donors, Red = Chicago)')
ax.legend(loc='upper left')

plt.tight_layout()

# Save
out_path = outdir / 'chicago_spaghetti_donors.png'
plt.savefig(out_path, dpi=150)
print(f"Saved: {out_path}")

plt.close()
