* Auto-generated by export_synth_data.py
* DO NOT EDIT - change settings in load_chatgpt_data.py

global outcome_var "log_trans"
global outcome_label "Log Transactions"
global outdir "/Users/jeffreyohl/Dropbox/LLM_PassThrough/output/trans/15to25/all_merchants"
