#!/usr/bin/env python3
"""Calculate transactions per user ratios and export as LaTeX macros."""

import sys
sys.path.insert(0, '/Users/jeffreyohl/Documents/GitHub/brainstorming')
from load_data import load_with_zip3
from pathlib import Path

# Load data
trans = load_with_zip3()
trans['month'] = trans['trans_date'].dt.to_period('M')

# Get sample end month
end_month = trans['month'].max()

def calc_metrics(df, label):
    """Calculate all metrics for a subset of transactions."""
    n_trans = len(df)
    n_users = df['cardid'].nunique()

    # Total trans per user (over whole sample)
    trans_per_user = n_trans / n_users

    # Active user-months: count of (user, month) pairs with transactions
    active_user_months = df.groupby(['cardid', 'month']).size().reset_index()
    n_active_user_months = len(active_user_months)
    trans_per_active_month = n_trans / n_active_user_months

    # Post-first-trans user-months: from first trans to end of sample
    first_month = df.groupby('cardid')['month'].min().reset_index()
    first_month.columns = ['cardid', 'first_month']

    # For each user: months from first_month to end_month (inclusive)
    def months_since_first(first_m):
        return (end_month - first_m).n + 1

    first_month['post_first_months'] = first_month['first_month'].apply(months_since_first)
    total_post_first_months = first_month['post_first_months'].sum()
    trans_per_post_first_month = n_trans / total_post_first_months

    print(f"\n{label}:")
    print(f"  Transactions: {n_trans:,}")
    print(f"  Unique users: {n_users:,}")
    print(f"  Active user-months: {n_active_user_months:,}")
    print(f"  Post-first-trans user-months: {total_post_first_months:,}")
    print(f"  ---")
    print(f"  Trans per user (total): {trans_per_user:.2f}")
    print(f"  Trans per active user-month: {trans_per_active_month:.2f}")
    print(f"  Trans per post-first user-month: {trans_per_post_first_month:.2f}")

    return {
        'n_trans': n_trans,
        'n_users': n_users,
        'n_active_user_months': n_active_user_months,
        'n_post_first_months': total_post_first_months,
        'trans_per_user': trans_per_user,
        'trans_per_active_month': trans_per_active_month,
        'trans_per_post_first_month': trans_per_post_first_month,
    }

# Calculate for full sample and Chicago
all_stats = calc_metrics(trans, "Full sample ($15-25, panel)")
chi_stats = calc_metrics(trans[trans['zip3'] == '606'], "Chicago (zip3 606)")

# Export macros
out_dir = Path('/Users/jeffreyohl/Dropbox/LLM_PassThrough/output/exploratory')
out_dir.mkdir(parents=True, exist_ok=True)
out_path = out_dir / 'trans_user_macros.tex'

with open(out_path, 'w') as f:
    f.write("% Auto-generated by trans_per_user_macros.py\n")
    f.write("% Transactions per user stats ($15-25 filter, constant panel)\n\n")

    f.write("% Full sample\n")
    f.write(f"\\newcommand{{\\transAll}}{{{all_stats['n_trans']:,}}}\n")
    f.write(f"\\newcommand{{\\usersAll}}{{{all_stats['n_users']:,}}}\n")
    f.write(f"\\newcommand{{\\transPerUserAll}}{{{all_stats['trans_per_user']:.2f}}}\n")
    f.write(f"\\newcommand{{\\transPerActiveMonthAll}}{{{all_stats['trans_per_active_month']:.2f}}}\n")
    f.write(f"\\newcommand{{\\transPerPostFirstMonthAll}}{{{all_stats['trans_per_post_first_month']:.2f}}}\n")
    f.write("\n")

    f.write("% Chicago (zip3 606)\n")
    f.write(f"\\newcommand{{\\transChi}}{{{chi_stats['n_trans']:,}}}\n")
    f.write(f"\\newcommand{{\\usersChi}}{{{chi_stats['n_users']:,}}}\n")
    f.write(f"\\newcommand{{\\transPerUserChi}}{{{chi_stats['trans_per_user']:.2f}}}\n")
    f.write(f"\\newcommand{{\\transPerActiveMonthChi}}{{{chi_stats['trans_per_active_month']:.2f}}}\n")
    f.write(f"\\newcommand{{\\transPerPostFirstMonthChi}}{{{chi_stats['trans_per_post_first_month']:.2f}}}\n")

print(f"\nSaved: {out_path}")
